version: '3.1'

services:
  selenium_chrome:
    image: selenium/standalone-chrome:3.13.0-argon
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
  okeanos_bot:
    container_name: okeanos_bot
    image: okeanos_bot
    build: .
    depends_on:
      - selenium_chrome
    volumes:
      - /home/user/okeanos_users:/data
    environment:
      NODE_ENV: production
      CREDENTIALS_FILE: /data/credentials.json
      SELENIUM_SERVER: http://selenium_chrome:4444/wd/hub
      BROWSER: chrome
      TOKENS_FILE: /data/tokens.json