version: '3.1'

services:
  selenium_chrome:
    image: selenium/standalone-chrome:3.13.0-argon
    volumes:
      - /dev/shm:/dev/shm
    deploy:
      resources:
        limits:
          cpus: '0.50'
        reservations:
          cpus: '0.25'
          memory: 100M
  okeanos_bot:
    container_name: okeanos_bot
    image: rambou/okeanos_bot
    depends_on:
      - selenium_chrome
    volumes:
      - /home/user/okeanos_users:/data
    environment:
      NODE_ENV: production
      CREDENTIALS_FILE: /data/credentials.json
      SELENIUM_SERVER: http://selenium_chrome:4444/wd/hub
      BROWSER: chrome
      LIMIT_CONCURRENT: 10
    links:
      - selenium_chrome:selenium_chrome
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: 150M
